import type { Metadata } from "next";
import { Playfair, Philosopher } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

export const philosopher = Philosopher({
  variable: "--font-philosopher",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const playfair = Playfair({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["300", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${playfair.className} ${philosopher.className}`}>
        <Header />
        <div className={`flex min-h-screen flex-col bg-[#f7f7f7] pt-10 ${philosopher.className}`}>
        {children}
        </div>
      </body>
    </html>
  );
}
