import type { Metadata } from "next";
import {Playfair, Philosopher } from "next/font/google";
import "./globals.css";

const philosopher = Philosopher({ subsets: ['latin'], weight: ['400', '700'] });
const playfair = Playfair({ subsets: ['latin'], weight: ['300', '900'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${philosopher.className} ${playfair.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
